name: aml_project
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=pyhf64b827_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.18.1=pyhcf101f3_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h29418f3_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py310h458dff3_0
  - bcrypt=5.0.0=py310h034784e_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hfd34d9b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.5=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_1
  - cftime=1.6.5=py310h8f3aa81_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cpython=3.10.19=py310hd8ed1ab_3
  - cryptography=46.0.3=py310hff68572_1
  - cycler=0.12.1=pyhcf101f3_2
  - databricks-sdk=0.81.0=pyhd8ed1ab_0
  - debugpy=1.8.19=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.128.0=h0ea4129_1
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.0=pyhcf101f3_1
  - filelock=3.20.3=pyhd8ed1ab_0
  - fiona=1.10.1=py310h73ae2b4_4
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.2=pyhcf101f3_0
  - fmt=12.1.0=h7f4e812_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=pyh7db6752_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - frozenlist=1.7.0=pyhf298e5d_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - geos=3.14.0=hdade9fe_0
  - geotiff=1.7.4=h86c3423_2
  - giflib=5.2.2=h64bf75a_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - google-auth=2.48.0=pyhcf101f3_0
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphite2=1.3.14=hac47afa_2
  - graphql-core=3.2.7=pyhcf101f3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.3.1=py310h73ae2b4_0
  - grpcio=1.73.1=py310hc77e67f_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.8.1=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py310hb7e4da9_101
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_h89f0904_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310h29418f3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huey=2.6.0=pyhcf101f3_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - invoke=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.5=haf901d7_0
  - libarchive=3.8.5=gpl_he24518a_100
  - libarrow=21.0.0=hcf7e2ff_16_cpu
  - libarrow-acero=21.0.0=h7d8d6a5_16_cpu
  - libarrow-compute=21.0.0=h2db994a_16_cpu
  - libarrow-dataset=21.0.0=h7d8d6a5_16_cpu
  - libarrow-substrait=21.0.0=hf865cc0_16_cpu
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_2
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgdal-core=3.10.3=h1dbae3e_18
  - libglib=2.86.2=hd9c3897_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hf3f85d1_8
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libnetcdf=4.9.3=nompi_h7d90bef_103
  - libparquet=21.0.0=h7051d1f_16_cpu
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - librttopo=1.1.0=h5ff11c1_19
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=h9d118f5_16
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h550210a_0
  - libtorch=2.10.0=cpu_mkl_hf431e7d_100
  - libutf8proc=2.11.3=hb980946_0
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxml2-devel=2.15.1=ha29bfb0_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mako=1.3.10=pyhcf101f3_1
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown=3.10.1=pyhcf101f3_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_455
  - mlflow=3.8.1=pyh7428d3b_0
  - mlflow-skinny=3.8.1=pyh7428d3b_0
  - mlflow-ui=3.8.1=pyh7428d3b_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=pyh62beb40_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=he0c23c2_0
  - mvlearn=0.5.0=pyhd8ed1ab_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.4=nompi_py310h0ae9510_102
  - networkx=3.4=pyhd8ed1ab_0
  - notebook=7.5.3=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py310hf667824_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - opentelemetry-api=1.39.1=pyhd8ed1ab_0
  - opentelemetry-proto=1.39.1=pyhd8ed1ab_0
  - opentelemetry-sdk=1.39.1=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.60b1=pyhd8ed1ab_0
  - optree=0.18.0=py310he9f1925_0
  - orc=2.2.2=hbd3206f_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py310h1c4a608_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310h712baa7_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - proj=9.6.2=h7990399_2
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=pyhe1237c8_0
  - protobuf=6.31.1=py310h81b7714_2
  - psutil=7.2.1=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py310h5588dad_2
  - pyarrow-core=21.0.0=py310hb6ca4c2_2_cpu
  - pyasn1=0.6.2=pyhd8ed1ab_0
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310h034784e_1
  - pydantic-extra-types=2.11.0=pyhd8ed1ab_0
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.2=py310h29418f3_0
  - pyogrio=0.11.0=py310hf80745b_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.1=py310h61ea1ad_1
  - pyside6=6.10.1=py310h96c60bd_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.10.19=hd8ed1ab_3
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-multipart=0.0.22=pyhcf101f3_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.10.0=cpu_mkl_py310_h2cce4df_100
  - pytorch-lightning=2.6.0=pyhcf101f3_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py310h282bd7d_1
  - pywin32-on-windows=0.1.0=pyh07e9846_2
  - pywinpty=2.0.15=py310h9e98ed7_1
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h7502b6c_0
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.3.1=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - rpds-py=0.30.0=py310h034784e_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=2.1.0=pyh6dadd2b_0
  - setuptools=80.10.2=pyh332efcf_0
  - shapely=2.1.2=py310h57f9f94_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sqlalchemy=2.0.46=py310h1637853_1
  - sqlite=3.51.2=hdb435a2_0
  - sqlparse=0.5.5=pyhcf101f3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - statsmodels=0.14.6=py310h8f3aa81_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=h3155e25_2
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h5588dad_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.18.1=pyh6dadd2b_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h6ed50ae_3
  - tomli=2.4.0=pyhcf101f3_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchvision=0.25.0=cpu_py310_h68b5f2f_1
  - tornado=6.5.4=py310h29418f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - uvicorn-standard=0.40.0=hcfb189c_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - waitress=3.0.2=pyhcf101f3_2
  - watchfiles=1.1.1=py310hf13f778_0
  - wcwidth=0.5.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=16.0=py310h1637853_1
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=2.0.1=py310h29418f3_1
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=pyh7db6752_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - affine==2.4.0
      - cca-zoo==2.6.0
      - cropharvest==0.7.0
      - et-xmlfile==2.0.0
      - geopandas==0.9.0
      - multiviewdata==0.7
      - nltk==3.9.2
      - openpyxl==3.1.5
      - rasterio==1.4.4
      - regex==2026.1.15
      - tensorly==0.9.0
      - torchaudio==2.10.0
      - torchtext==0.18.0
      - xarray==0.19.0
prefix: C:\Users\m_jer\miniforge3\envs\aml_project
